# Generated by Django 4.0.3 on 2022-04-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='typ',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
