# Generated by Django 4.0.3 on 2022-04-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='typ',
            field=models.CharField(default='action', max_length=100),
        ),
    ]
